// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvwwxjpiidwuzkhyatzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2d3d4anBpaWR3dXpraHlhdHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDg0NjAsImV4cCI6MjA2NDYyNDQ2MH0.5NLSSGzHR9SAkCYRnjnE-ClzGPESKMBh5gqyf7nsXK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);